server:
  port: 8080
  servlet:
    context-path: /

  # serverTimezone=Asia/Shanghai  时区
  # useUnicode=true               使用Unicode编码
  # characterEncoding=utf8        使用utf-8字符集
  # autoReconnect=true            是否重新连接
  # allowMultiQueries=true        是否批量操作，即可以执行多个SQL
spring:
  datasource:
    url: jdbc:mariadb://localhost:3309/jt?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/templates/   #设置页面前缀
    suffix: .html                   #设置页面后缀
    cache: false                    #是否使用缓存
  mvc:
    hiddenmethod:
      filter:
        enabled: true               #使用restFu需要开启此配置

# mybatis-plush配置
mybatis-plus:
  type-aliases-package: com.demo.pojo     # 别名，省去写全类名
  mapper-locations: classpath:/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰映射

logging:
  level:
    com.demo.mapper: debug      # 开启sql日志输出，cn.jt.mapper是存放mapper接口文件的目录
