server:
  port: 8080

# \u914D\u7F6E\u6A21\u677F\u5DE5\u5177\u7C7B
spring:
  thymeleaf:
    prefix: classpath:/templates/   #\u8BBE\u7F6E\u9875\u9762\u524D\u7F00
    suffix: .html                   #\u8BBE\u7F6E\u9875\u9762\u540E\u7F00
    cache: false                    #\u662F\u5426\u4F7F\u7528\u7F13\u5B58
